services:
   health-traker:
      image: health-traker:${VERSION:-latest}
      environment:
         - ASPNETCORE_ENVIRONMENT=Development
      ports:
         - "33030:80"
      build:
         context: .
         dockerfile: Service/Dockerfile
