services:
   health-traker:
      image: health-traker:${VERSION:-latest}
      env_file:
         - ./.env
      ports:
         - "33030:80"
      build:
         context: .
         dockerfile: Service/Dockerfile
