services:
   postgres-data:
      image: postgres:alpine
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=docker
      ports:
         - "5432:5432"
      volumes:
         - ./init.sql:/docker-entrypoint-initdb.d/init.sql

   timescaledb:
      container_name: timescaledb
      image: timescale/timescaledb-ha:pg15-all
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=health_tracker
      restart: unless-stopped
      volumes:
         - "/timescale/timescaledb/pgdata:/home/postgres/pgdata"
         - "/timescale/oldtimescale:/mnt/olddata"